#pragma 				tabsize 					(0)

//Sistema de registro
#define 				RegisterDialog 				(1)
#define 				LoginDialog 				(2)
#define					RegisterSex					(3)
#define					RegisterAge					(4)
#define 				SuccessRegister 			(5)
#define 				SuccessLogin 				(6)

//Dialogos
#define					KEY_DIALOG					(7)

//ID staff
#define					Usuario						(0)
#define					Ayudante					(1)
#define					Moderador					(2)
#define					Administrador				(3)
#define					Programador					(4)
#define					Dueno						(5)
#define					COLOR_USUARIO				0xEFEFEFFF
#define					COLOR_AYUDANTE				0x006780FF
#define					COLOR_MODERADOR				0x00CD23FF
#define					COLOR_ADMINISTRADOR			0xDE0023FF
#define					COLOR_PROGRAMADOR			0x00FFD6FF
#define					COLOR_DUEÑO					0xEE3AC1FF

//Sistema de facciones
#define					MAX_FACTIONS				(15)
new COUNT_FACTIONS = 0;
#define					MiembroF					(1)
#define					CapitanF					(2)
#define					ColiderF					(3)
#define					LiderF						(4)

//Colores
#define					COLOR_WHITE_T				"{FFFFFF}"
#define					COLOR_RED_T					"{F81414}"
#define					COLOR_GREEN_T				"{00FF22}"
#define					COLOR_BLACK					0x000000FF
#define					COLOR_WHITE					0xFAFAFAFF
#define					COLOR_YELLOW				0xE6E915FF
#define					COLOR_RED 					0xE60000FF
#define					COLOR_PURPLE				0xC2A2DAAA
#define					COLOR_GREEN					0x9EC73DAA
#define					COLOR_FADE1					0xE6E6E6E6
#define					COLOR_FADE2					0xC8C8C8C8
#define					COLOR_FADE3					0xAAAAAAAA
#define					COLOR_FADE4					0x8C8C8C8C
#define					COLOR_FADE5					0x6E6E6E6E

//Limites
#define					MAX_PING					(1500)